#!/bin/bash

# Derived from:
# Cronic v3 - cron job report wrapper
# Copyright 2007-2016 Chuck Houpt. No rights reserved, whatsoever.
# Public Domain CC0: http://creativecommons.org/publicdomain/zero/1.0/
#
#  Adds support for --always option and can eval multi-statement commands

set -eu

TMP=$(mktemp -d)
OUT=$TMP/cronic.out
ERR=$TMP/cronic.err
TRACE=$TMP/cronic.trace

ALWAYS=0
if [ "$1" = "--always" ]
then
    ALWAYS=1
    shift
fi

set +e
eval "$@" >$OUT 2>$TRACE
RESULT=$?
set -e

PATTERN="^${PS4:0:1}\\+${PS4:1}"
if grep -aq "$PATTERN" $TRACE
then
    ! grep -av "$PATTERN" $TRACE > $ERR
else
    ERR=$TRACE
fi

HAS_ERROR=1
[ $RESULT -ne 0 -o -s "$ERR" ] || HAS_ERROR=0

if [ $ALWAYS -eq 1 -o "$HAS_ERROR" -eq 1 ]
    then
    if [ "$HAS_ERROR" -eq 1 ]
    then
	echo "Cronic detected failure or error output for the command:"
    else
	echo "Cronic successfully ran the command:"
    fi
    echo "$@"
    echo
    echo "RESULT CODE: $RESULT"
    echo
    echo "ERROR OUTPUT:"
    cat "$ERR"
    echo
    echo "STANDARD OUTPUT:"
    cat "$OUT"
    if [ $TRACE != $ERR ]
    then
        echo
        echo "TRACE-ERROR OUTPUT:"
        cat "$TRACE"
    fi
fi

rm -rf "$TMP"
